name: Matrix Build, Test, and Docker Push with Vault

on:
  push:
    branches: [ "main", "develop", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11, 17]
      fail-fast: false  # Continue other matrix jobs even if one fails

    steps:
    - uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar-${{ matrix.os }}-java${{ matrix.java }}
        path: target/*.jar
        retention-days: 3

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: target/
      
      - name: Display structure of downloaded files
        run: ls -R target/

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Fetch Docker credentials from Vault
      - name: Fetch Docker credentials from Vault
        env:
          VAULT_ADDR: "http://65.0.135.239:8200"
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          echo "Reading Docker credentials from Vault..."
          SECRET_JSON=$(curl --header "X-Vault-Token: $VAULT_TOKEN" \
                             --silent \
                             --request GET \
                             $VAULT_ADDR/v1/kv/data/docker_cred)
          
          echo "Parsing credentials..."
          DOCKER_USERNAME=$(echo $SECRET_JSON | jq -r '.data.data.DOCKER_USERNAME')
          DOCKER_PASSWORD=$(echo $SECRET_JSON | jq -r '.data.data.DOCKER_PASSWORD')
          
          # Mask secrets
          echo "::add-mask::$DOCKER_USERNAME"
          echo "::add-mask::$DOCKER_PASSWORD"
          
          echo "DOCKER_USERNAME=$DOCKER_USERNAME" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=$DOCKER_PASSWORD" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Images
        env:
          DOCKER_IMAGE_NAME: "spring-boot-hello-world-for-kamran"
        run: |
          echo "Building Docker image..."
          docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${GITHUB_SHA} .
          docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest .
          
          echo "Pushing Docker images..."
          docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${GITHUB_SHA}
          docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
