name: Build with Cache and Artifacts Demo

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Example of explicit Maven dependency caching
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Example of multiple artifact uploads
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: target/*.jar
        retention-days: 5
        compression-level: 9

    - name: Upload Test Reports
      if: always()  # Upload even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 1
        compression-level: 6

  # Example of artifact download in another job
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Display structure of downloaded files
        run: ls -R target/
