name: Reusable Build & Test Workflow

on:
  workflow_call:
    inputs:
      java-versions:
        required: true
        type: string
      os-list:
        required: true
        type: string

jobs:
  build-test:
    name: Build & Test on ${{ matrix.os }} with Java ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os-list) }}
        java: ${{ fromJson(inputs.java-versions) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # Setup Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Fix Windows Temp Path
      - name: Fix Windows Temp Path
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "TEMP=D:\\temp" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TMP=D:\\temp" | Out-File -FilePath $env:GITHUB_ENV -Append
          New-Item -ItemType Directory -Force -Path D:\temp

      # Set Maven Options
      - name: Set Maven Options
        run: echo "MAVEN_OPTS=-Xmx1024m -Djava.io.tmpdir=$RUNNER_TEMP" >> $GITHUB_ENV

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build & Test
      - name: Build and Test with Maven
        run: mvn -B clean verify --file pom.xml

      # Upload JAR (only from Ubuntu)
      - name: Upload Build Artifact
        if: matrix.os == 'ubuntu-latest' && matrix.java == '8'
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 5
          compression-level: 9

      # Upload Test Reports
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports/
          retention-days: 2
          compression-level: 6
